### ISSUE TITLE
Revisión y comprensión src 

### ISSUE THREAD

**Issue by ArturoSirvent** [mvanzulli/Meeting_Assistant#27]
Voy a revisar todo el trabajo de Mauricio para aprender de lo bien que trabaja. :D

**Comment by ArturoSirvent** [comment]
Observaciones para cumplir con los patrones de diseño SOLID (lo pongo más como ejercicio personal de analisis, no hace falta ni mucho menos cumplirlo todo, sería casi overshooting).  
- En la clase Meeting las acciones concretas como record o transcribe, no deberían establecerse concretamente, sino por medio de abstracciones (interfaces).  
- Y si se pueden separar en clases mejor (principio S).
- Answer es un método que podía abarcar una clase propia por la complejidad que puede terminar teniendo.  
- Segun el principio DIP una abstracción no debería depender de detalles, eso ocurren en AbstractRecorder con el display_clock.
- Quiza el propio audio podía tener su propia clase que lo enmarcara.
- Transcription debe heredar de la clase abstracta. 
- Quizá, según el ISP, deberíamos segregar los métodos de la abstracción AbstractTranscription(), esto va en la linea de que anwser() quizá es demasiado complejo para estar dentro del propio Metting class. 
- Duda ¿Se podría poner un Abstract attribute a.k.a property, para el lang. de la transcripcion?   
- Si se crea un objeto transcription ya estamos asumiendo que vamos a trabajar con el texto de la transcripcion, de modo que get_text() quiza podía ser parte de la inicializacion del objeto y que self.text ya estuviera disponible una vez creado.

**Comment by mvanzulli** [comment]
Gracias por todos los comentarios,  abarcan muchos puntos para intercambiar sobre ellos:
> 
> * En la clase Meeting las acciones concretas como record o transcribe, no deberían establecerse concretamente, sino por medio de abstracciones (interfaces).
Si, se puede definir una clase abastracta de `AbstractMeeting` definiendo la interfaz. Eso nos permitiería luego tener un template de lo que debe tener un meeting. Estoy de acuerdo si querés agregarlo al código. 

> * Y si se pueden separar en clases mejor (principio SRP).
Decis separar en subclases lo que está dentro del meeting ? Eso lo veo un poco Overengineering by the moment. 
 

> * Segun el principio DIP una abstracción no debería depender de detalles, eso ocurren en AbstractRecorder con el display_clock.
Muy buena observación, totalmente de acuerdo. Propongo que abras un issue con esto!


> * De hecho, el DIP también aplica en el caso de answer, ne deberíamos depender en QAGPT que es una aplicación concreta, deberíamos depender en una abstracción que tenga los metodos que necesitamos para responder. En general Meeting podría cumplir mejor el SRP.
Esto me parece una muy buena idea, creo que la clase QABot es la que busca cumplir con la abstracción. Lo que se puede hacer aquí es que cuando se crea el objeto meeting haya que definir un QABot basado en algún modelo de lenguaje. La imeplentación de answer debería ir a buscar ese QABot y responder. 


> * Quiza el propio audio podía tener su propia clase que lo enmarcara.
> * Transcription debe heredar de la clase abstracta.
> * Quizá, según el ISP, deberíamos segregar los métodos de la abstracción AbstractTranscription(), esto va en la linea de que anwser() quizá es demasiado complejo para estar dentro del propio Metting class.
Tremendo, muy buen aporte estoy de acuerdo. 

> * Duda ¿Se podría poner un Abstract attribute a.k.a property, para el lang. de la transcripcion?
> * Si se crea un objeto transcription ya estamos asumiendo que vamos a trabajar con el texto de la transcripcion, de modo que get_text() quiza podía ser parte de la inicializacion del objeto y que self.text ya estuviera disponible una vez creado.
Eso duplicaría la memoria pero disminuiría el tiempo computacional. El objeto Transcription hoy en dia guarda segmentos (que también podrían ser objetos que incluyen texto y tiempo). Todo el texto se puede guardar en un atributo pero no estoy completamente seguro, quizás podemos discutir pros y cons de esto.

**Comment by mvanzulli** [comment]
@ArturoSirvent  adelante con los cambios que te parezcan 👍🏼 , la seguimos por PR. Sugiero ir abriendo de a uno para dar una revisión a los cambios. Luego tests, y luego en otro docs. ( lo podemos transofmar en issues para más adelante )

**Comment by ArturoSirvent** [comment]
duda:

definir init como clase abstracta no da un error?  

```
class AbstractQABot(ABC):
    """Abstract base class for a question and answer bot."""

    @abstractmethod
    def __init__(self, *args, **kwargs):
        pass

```   
*TypeError: Can't instantiate abstract class b with abstract method __init__*

**Comment by ArturoSirvent** [comment]
Estaba pensado abrir un issue para que la selección del modelo sea más sencilla, y no limitarnos a gpt.

**Comment by mvanzulli** [comment]
> duda:
> 
> definir init como clase abstracta no da un error?
> 
> ```
> class AbstractQABot(ABC):
>     """Abstract base class for a question and answer bot."""
> 
>     @abstractmethod
>     def __init__(self, *args, **kwargs):
>         pass
> ```
> 
> _TypeError: Can't instantiate abstract class b with abstract method **init**_

This works for me
```py
import abc

class AbstractQABot(abc.ABC):
     """Abstract base class for a question and answer bot."""

     @abc.abstractmethod
     def __init__(self, *args, **kwargs):
         pass
```

**Comment by mvanzulli** [comment]
> Estaba pensado abrir un issue para que la selección del modelo sea más sencilla, y no limitarnos a gpt.

Me parece excelente, armo un issue

**Comment by ArturoSirvent** [comment]
De este issue se saca en claro lo siguiente:   
- Creación de una clase meeting más general. Esto de vistas a tener diferentes tipos de meeting: Conferencia, charla, reunión formal, entrevista... (src/meeting_assistant/meetings.py)  No se como esto puede relacionarse con el MeetingModel que se define en la API (api/models.py).    
- Generalizar el modelo usado, que pueda ser cualquiera cumpliendo con una interfaz básica de interacción. Este es el issue #30 
- "display_clock" en abstract_recorder queda un poco raro.(Abro issue)  
- El QABot debería ser algo que implemente answer, y que use un modelo. En lugar de que sea la concretizacion de QABotGPT el que implemente answer. Sino tendremos una implementación de answer por cada modelo que añadamos. (Abro issue)
